#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

security:
  apiKey: "1234"
  basic:
    enabled: false

storage:
  entities:
    path: "D:/Graphen/entities"
  transactions:
    path: "D:/Graphen/transactions"
  schema:
    path: "D:/Graphen/schema"

spring:
  security:
    user:
      name: "user"
      password: "password"

logging:
  level:
    com:
      bechtle: TRACE
    org:
      springframework:
        security: INFO


management:
  endpoints:
    web:
      exposure:
        include: "health, info, env, loggers, metrics, scheduledTasks, logfile, mappings"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    scheduledTasks:
      enabled: true
    logfile:
      enabled: true