## All XXX fields are provisioned through environment variables


application: 
  features:
    schedulers:
      detectDuplicates: true
      replaceGlobalIdentifiers: true
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
    validators:
      checkRequiredType: true
  storage:
    default:
      persistent: true    
      path: "/var/data/application"
    entities:
      persistent: true        
      path: "/var/data/entities"
    transactions:
      persistent: true        
      path: "/var/data/transactions"



