#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo




server:
  port : 8070

logging:
  level:
    com:
      bechtle: INFO
    org:
      springframework:
        security: INFO

features:
  schedulers:
    detectDuplicates: false
    replaceGlobalIdentifiers: false
  transformers:
    replaceGlobalIdentifiers: true
    replaceAnonymousIdentifiers: true
    mergeDuplicates: true
  validators:
    checkRequiredType: true



