#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


server:
  port : 8070

logging:
  level:
    com:
      bechtle: INFO
    org:
      springframework:
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health, info, env, loggers, metrics, scheduledTasks, logfile, mappings"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    scheduledTasks:
      enabled: true
    logfile:
      enabled: true



