#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


server:
  port : 8070


spring:
  profiles:
    active: local


defaults:
  namespace:
    transactions: "http://www.av360.io/schema/transactions#"
    entities: "http://www.av360.io/schema/entities/"





