#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo

application:
  security:
    enabled: true
    apiKey: ""
    basic:
      enabled: false
  features:
    schedulers:
      detectDuplicates: false
      replaceGlobalIdentifiers: false
    transformers:
      replaceGlobalIdentifiers: true
      replaceAnonymousIdentifiers: true
      mergeDuplicates: true
    validators:
      checkRequiredType: true
  storage:
    default:
      persistent: false
      path: {}
    entities:
      persistent: false
      path: {}
    transactions:
      persistent: false
      path: {}

logging:
  level:
    com:
      bechtle: TRACE
    org:
      springframework:
        security: TRACE

