#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo


application:
  security:
    enabled: true
    basic:
      enabled: false
  features:
    schedulers:
      detectDuplicates: false
      replaceGlobalIdentifiers: false
    transformers:
      replaceGlobalIdentifiers: false
      replaceAnonymousIdentifiers: false
      mergeDuplicates: false
    validators:
      checkRequiredType: false
  storage:
    default:
      persistent: false
      path: ~
    entities:
      persistent: false
      path: ~
    transactions:
      persistent: false
      path: ~

server:
  port : 8070

logging:
  level:
    graph: TRACE
    org:
      springframework:
        security: INFO



