plugins:
  - git-committers:
      repository: squidfunk/mkdocs-material
      branch: main

plugins:
  - git-committers:
      enabled: !ENV [CI, false]

plugins:
  - git-committers:
      repository: squidfunk/mkdocs-material

